// Supabase設定
const { createClient } = require('@supabase/supabase-js');

// 環境変数から設定を読み込む
const supabaseUrl = process.env.SUPABASE_URL || 'https://huatolfthmihcpzjpyipd.supabase.co';
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1YXRvbGZ0aG1pY3B6anB5aXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU0Nzg4NzUsImV4cCI6MjA3MzUwMDg3NX0._';

// Supabaseクライアントを作成
const supabase = createClient(supabaseUrl, supabaseServiceKey);

// CORSヘルパー
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS'
};

// APIハンドラー
exports.handler = async (req, res) => {
  // プリフライトリクエストの処理
  if (req.method === 'OPTIONS') {
    return res.status(200).set(corsHeaders).end();
  }

  res.set(corsHeaders);

  try {
    switch (req.method) {
      case 'GET':
        await handleGet(req, res);
        break;
      case 'POST':
        await handlePost(req, res);
        break;
      default:
        res.status(405).json({ error: 'Method not allowed' });
    }
  } catch (error) {
    console.error('API Error:', error);
    res.status(500).json({ error: 'Internal server error', message: error.message });
  }
};

// GETリクエストの処理
async function handleGet(req, res) {
  const { path } = req.query;

  switch (path) {
    case 'test-connection':
      // 接続テスト
      const { data: testData, error: testError } = await supabase
        .from('news')
        .select('count')
        .limit(1);

      if (testError && testError.code === 'PGRST116') {
        return res.status(404).json({
          success: false,
          message: 'newsテーブルが存在しません。CREATE TABLEを実行してください。',
          sql: `CREATE TABLE public.news (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            date TEXT NOT NULL,
            content TEXT NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
          );

          ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

          CREATE POLICY "Public access to news" ON public.news
            FOR SELECT USING (true);`
        });
      } else if (testError) {
        throw testError;
      } else {
        return res.json({
          success: true,
          message: 'Supabase接続成功！',
          tableExists: true
        });
      }

    case 'news':
      // ニュースデータの取得
      const { data, error } = await supabase
        .from('news')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;

      return res.json({
        success: true,
        data: data || [],
        count: data ? data.length : 0
      });

    default:
      res.status(404).json({ error: 'Endpoint not found' });
  }
}

// POSTリクエストの処理
async function handlePost(req, res) {
  const { path } = req.query;
  const body = req.body;

  switch (path) {
    case 'news':
      // ニュースデータの作成
      if (!body.title || !body.date || !body.content) {
        return res.status(400).json({
          success: false,
          error: 'title, date, content は必須です'
        });
      }

      const { data, error } = await supabase
        .from('news')
        .insert([{
          title: body.title,
          date: body.date,
          content: body.content
        }])
        .select();

      if (error) throw error;

      return res.json({
        success: true,
        message: 'ニュースが作成されました',
        data: data
      });

    default:
      res.status(404).json({ error: 'Endpoint not found' });
  }
}