// Supabase設定
const { createClient } = require('@supabase/supabase-js');

// 環境変数から設定を読み込む
const supabaseUrl = process.env.SUPABASE_URL || 'https://huatolfthmihcpzjpyipd.supabase.co';
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1YXRvbGZ0aG1pY3B6anB5aXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU0Nzg4NzUsImV4cCI6MjA3MzUwMDg3NX0._';

// Supabaseクライアントを作成
const supabase = createClient(supabaseUrl, supabaseServiceKey);

// CORSヘルパー
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS'
};

exports.handler = async (req, res) => {
  // プリフライトリクエストの処理
  if (req.method === 'OPTIONS') {
    return res.status(200).set(corsHeaders).end();
  }

  res.set(corsHeaders);

  try {
    // テーブルが存在するか確認
    const { data: testData, error: testError } = await supabase
      .from('news')
      .select('count')
      .limit(1);

    if (testError && testError.code === 'PGRST116') {
      // テーブルが存在しないので作成
      console.log('newsテーブルが存在しないので作成します...');

      // 手動でテーブルを作成
      const { data: createData, error: createError } = await supabase
        .rpc('exec_sql', {
          sql: `CREATE TABLE IF NOT EXISTS public.news (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            date TEXT NOT NULL,
            content TEXT NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
          );

          ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

          CREATE POLICY IF NOT EXISTS "Public access to news" ON public.news
            FOR SELECT USING (true);`
        });

      if (createError) {
        // RPCが失敗した場合のフォールバック（直接SQL実行できない場合）
        // 実際のアプリケーションでは、Supabase SQL Editorで事前にテーブルを作成するか、
        // migrations機能を使うことを推奨します
        console.error('テーブル作成エラー:', createError);
        return res.status(500).json({
          success: false,
          message: 'テーブル作成に失敗しました。手動でSQLを実行してください。',
          error: createError.message,
          manual_sql: `-- Supabase SQL Editorで実行してください：
          CREATE TABLE public.news (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            date TEXT NOT NULL,
            content TEXT NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
          );

          ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

          CREATE POLICY "Public access to news" ON public.news
            FOR SELECT USING (true);`
        });
      }

      return res.json({
        success: true,
        message: 'newsテーブルが作成されました！',
        data: createData
      });
    } else if (testError) {
      throw testError;
    } else {
      // テーブルは既に存在する
      return res.json({
        success: true,
        message: 'newsテーブルは既に存在します',
        tableExists: true
      });
    }
  } catch (error) {
    console.error('Database initialization error:', error);
    res.status(500).json({
      success: false,
      error: error.message,
      message: 'データベース初期化中にエラーが発生しました'
    });
  }
};